Repository ShipDoc/Backend, pull requests merged in 2024-05, with the labels that each got.

#2 👷 CI. CI/CD 파이프라인 구축
  .github/workflows/gradle.yml
  Dockerfile
  build.gradle
Labels: :sparkles: feature, :construction_worker: ci/cd

#4 ✨ FEAT. 회원가입, JWT 토큰 기반 인증 구현
  build.gradle
  src/main/java/com/shipdoc/ShipdocApplication.java
  src/main/java/com/shipdoc/domain/Member/converter/MemberConverter.java
  src/main/java/com/shipdoc/domain/Member/entity/Member.java
  src/main/java/com/shipdoc/domain/Member/entity/Role.java
  src/main/java/com/shipdoc/domain/Member/entity/mapping/MemberRole.java
  src/main/java/com/shipdoc/domain/Member/enums/Authority.java
  src/main/java/com/shipdoc/domain/Member/repository/MemberRepository.java
  src/main/java/com/shipdoc/domain/Member/repository/RoleRepository.java
  src/main/java/com/shipdoc/domain/Member/service/MemberCommandService.java
  src/main/java/com/shipdoc/domain/Member/service/MemberCommandServiceImpl.java
  src/main/java/com/shipdoc/domain/Member/service/MemberQueryService.java
  src/main/java/com/shipdoc/domain/Member/service/MemberQueryServiceImpl.java
  src/main/java/com/shipdoc/domain/Member/validation/annotation/PasswordMatch.java
  src/main/java/com/shipdoc/domain/Member/validation/validator/PasswordMatchValidator.java
  src/main/java/com/shipdoc/domain/Member/web/controller/MemberRestController.java
  src/main/java/com/shipdoc/domain/Member/web/dto/MemberRequestDto.java
  src/main/java/com/shipdoc/domain/Member/web/dto/MemberResponseDto.java
  src/main/java/com/shipdoc/global/config/SecurityConfig.java
  src/main/java/com/shipdoc/global/entity/BaseEntity.java
  src/main/java/com/shipdoc/global/enums/statuscode/BaseCode.java
  src/main/java/com/shipdoc/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/shipdoc/global/enums/statuscode/SuccessStatus.java
  src/main/java/com/shipdoc/global/exception/ExceptionAdvice.java
  src/main/java/com/shipdoc/global/exception/GeneralException.java
  src/main/java/com/shipdoc/global/response/ApiResponse.java
  src/main/java/com/shipdoc/global/security/LoginService.java
  src/main/java/com/shipdoc/global/security/jwt/JwtService.java
  src/main/java/com/shipdoc/global/security/jwt/filter/CustomUsernamePwdAuthenticationFilter.java
  src/main/java/com/shipdoc/global/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/shipdoc/global/security/jwt/handler/JwtLoginFailureHandler.java
  src/main/java/com/shipdoc/global/security/jwt/handler/JwtLoginSuccessHandler.java
Labels: :sparkles: feature

#7 ✨ FEAT. 증상, 병원 카테고리에 따른 주변 검색 기능 구현
  src/main/java/com/shipdoc/domain/search/converter/SearchConverter.java
  src/main/java/com/shipdoc/domain/search/enums/HospitalSortCriteria.java
  src/main/java/com/shipdoc/domain/search/enums/MedicalDepartment.java
  src/main/java/com/shipdoc/domain/search/enums/Symptom.java
  src/main/java/com/shipdoc/domain/search/service/SearchQueryService.java
  src/main/java/com/shipdoc/domain/search/service/SearchQueryServiceImpl.java
  src/main/java/com/shipdoc/domain/search/validation/annotation/CategoryKeyword.java
  src/main/java/com/shipdoc/domain/search/validation/validator/CategoryKeywordValidator.java
  src/main/java/com/shipdoc/domain/search/web/controller/SearchRestController.java
  src/main/java/com/shipdoc/domain/search/web/dto/SearchRequestDto.java
  src/main/java/com/shipdoc/domain/search/web/dto/SearchResponseDto.java
  src/main/java/com/shipdoc/global/kakao/NearbySearchService.java
  src/main/java/com/shipdoc/global/kakao/dto/KakaoResponseDto.java
Labels: :sparkles: feature

#8 ✨ FEAT. LoginMember ArgumentResolver 구현
  src/main/java/com/shipdoc/domain/Member/exception/MemberNotExistException.java
  src/main/java/com/shipdoc/global/annotation/LoginMember.java
  src/main/java/com/shipdoc/global/config/WebConfig.java
  src/main/java/com/shipdoc/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/shipdoc/global/resolver/LoginMemberArgumentResolver.java
Labels: :sparkles: feature

#17 ✨ FEAT. 환자(자녀) 추가, 삭제 기능 구현
  src/main/java/com/shipdoc/domain/Member/converter/MemberConverter.java
  src/main/java/com/shipdoc/domain/Member/entity/Member.java
  src/main/java/com/shipdoc/domain/Member/entity/Patient.java
  src/main/java/com/shipdoc/domain/Member/entity/mapping/Reservation.java
  src/main/java/com/shipdoc/domain/Member/enums/FamilyRelation.java
  src/main/java/com/shipdoc/domain/Member/enums/NationalityType.java
  src/main/java/com/shipdoc/domain/Member/exception/PatientNotExistException.java
  src/main/java/com/shipdoc/domain/Member/repository/PatientRepository.java
  src/main/java/com/shipdoc/domain/Member/service/MemberCommandService.java
  src/main/java/com/shipdoc/domain/Member/service/MemberCommandServiceImpl.java
  src/main/java/com/shipdoc/domain/Member/service/MemberQueryService.java
  src/main/java/com/shipdoc/domain/Member/validation/annotation/ValidateRRN.java
  src/main/java/com/shipdoc/domain/Member/validation/validator/ValidateRRNValidator.java
  src/main/java/com/shipdoc/domain/Member/web/controller/MemberRestController.java
  src/main/java/com/shipdoc/domain/Member/web/dto/MemberRequestDto.java
  src/main/java/com/shipdoc/domain/Member/web/dto/MemberResponseDto.java
  src/main/java/com/shipdoc/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: feature

#19 ✨ FEAT. 회원가입 시 생년월일, 이름 데이터 추가
  src/main/java/com/shipdoc/domain/Member/converter/MemberConverter.java
  src/main/java/com/shipdoc/domain/Member/repository/PatientRepository.java
  src/main/java/com/shipdoc/domain/Member/service/MemberCommandServiceImpl.java
  src/main/java/com/shipdoc/domain/Member/web/dto/MemberRequestDto.java
Labels: :bug: fix, :sparkles: feature

#20 ✨ FEAT. 예약 기능 API 구현
  src/main/java/com/shipdoc/domain/Member/entity/Patient.java
  src/main/java/com/shipdoc/domain/Member/entity/mapping/Reservation.java
  src/main/java/com/shipdoc/domain/Member/service/MemberCommandServiceImpl.java
  src/main/java/com/shipdoc/domain/hospital/exception/HospitalNotExistException.java
  src/main/java/com/shipdoc/domain/reservation/converter/ReservationConverter.java
  src/main/java/com/shipdoc/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/shipdoc/domain/reservation/service/ReservationCommandService.java
  src/main/java/com/shipdoc/domain/reservation/service/ReservationCommandServiceImpl.java
  src/main/java/com/shipdoc/domain/reservation/validation/annotation/PhoneNumber.java
  src/main/java/com/shipdoc/domain/reservation/validation/validator/PhoneNumberValidator.java
  src/main/java/com/shipdoc/domain/reservation/web/controller/ReservationRestController.java
  src/main/java/com/shipdoc/domain/reservation/web/dto/ReservationRequestDto.java
  src/main/java/com/shipdoc/domain/reservation/web/dto/ReservationResponseDto.java
  src/main/java/com/shipdoc/global/config/SecurityConfig.java
  src/main/java/com/shipdoc/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/shipdoc/global/security/jwt/filter/JwtAuthenticationFilter.java
Labels: :bug: fix, :sparkles: feature

#22 ✨ FEAT. 리뷰 관련 API 기능 구현
  src/main/java/com/shipdoc/domain/Member/converter/MemberConverter.java
  src/main/java/com/shipdoc/domain/Member/entity/Member.java
  src/main/java/com/shipdoc/domain/Member/entity/mapping/ReviewRecommend.java
  src/main/java/com/shipdoc/domain/hospital/converter/HospitalConverter.java
  src/main/java/com/shipdoc/domain/hospital/converter/ReviewConverter.java
  src/main/java/com/shipdoc/domain/hospital/entity/mapping/Review.java
  src/main/java/com/shipdoc/domain/hospital/enums/ReviewSortStatus.java
  src/main/java/com/shipdoc/domain/hospital/exception/ReviewNotExistException.java
  src/main/java/com/shipdoc/domain/hospital/repository/HospitalRepository.java
  src/main/java/com/shipdoc/domain/hospital/repository/ReviewRecommendRepository.java
  src/main/java/com/shipdoc/domain/hospital/repository/ReviewRepository.java
  src/main/java/com/shipdoc/domain/hospital/service/HospitalQueryService.java
  src/main/java/com/shipdoc/domain/hospital/service/HospitalQueryServiceImpl.java
  src/main/java/com/shipdoc/domain/hospital/service/ReviewCommandService.java
  src/main/java/com/shipdoc/domain/hospital/service/ReviewCommandServiceImpl.java
  src/main/java/com/shipdoc/domain/hospital/web/controller/HospitalRestController.java
  src/main/java/com/shipdoc/domain/hospital/web/controller/ReviewRestController.java
  src/main/java/com/shipdoc/domain/hospital/web/dto/HospitalResponseDto.java
  src/main/java/com/shipdoc/domain/hospital/web/dto/ReviewRequestDto.java
  src/main/java/com/shipdoc/domain/hospital/web/dto/ReviewResponseDto.java
  src/main/java/com/shipdoc/domain/reservation/web/controller/ReservationRestController.java
  src/main/java/com/shipdoc/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/shipdoc/global/security/jwt/handler/JwtLoginFailureHandler.java
  src/main/java/com/shipdoc/global/validation/annotation/PageableVariable.java
  src/main/java/com/shipdoc/global/validation/validator/PageableVariableConstraint.java
Labels: :sparkles: feature

#24 ♻️ REFACTOR. 응답 DTO 변경 및 병원 상세 페이지 조회 API 구현
  src/main/java/com/shipdoc/domain/hospital/converter/HospitalConverter.java
  src/main/java/com/shipdoc/domain/hospital/entity/BusinessHours.java
  src/main/java/com/shipdoc/domain/hospital/entity/Hospital.java
  src/main/java/com/shipdoc/domain/hospital/service/HospitalCommandService.java
  src/main/java/com/shipdoc/domain/hospital/service/HospitalCommandServiceImpl.java
  src/main/java/com/shipdoc/domain/hospital/service/HospitalQueryService.java
  src/main/java/com/shipdoc/domain/hospital/service/HospitalQueryServiceImpl.java
  src/main/java/com/shipdoc/domain/hospital/service/ReviewQueryService.java
  src/main/java/com/shipdoc/domain/hospital/service/ReviewQueryServiceImpl.java
  src/main/java/com/shipdoc/domain/hospital/web/controller/HospitalRestController.java
  src/main/java/com/shipdoc/domain/hospital/web/dto/HospitalResponseDto.java
  src/main/java/com/shipdoc/domain/search/converter/SearchConverter.java
  src/main/java/com/shipdoc/domain/search/enums/HospitalSortCriteria.java
  src/main/java/com/shipdoc/domain/search/enums/HospitalSortStatus.java
  src/main/java/com/shipdoc/domain/search/service/SearchQueryService.java
  src/main/java/com/shipdoc/domain/search/service/SearchQueryServiceImpl.java
  src/main/java/com/shipdoc/domain/search/web/controller/SearchRestController.java
  src/main/java/com/shipdoc/domain/search/web/dto/SearchRequestDto.java
  src/main/java/com/shipdoc/domain/search/web/dto/SearchResponseDto.java
  src/main/java/com/shipdoc/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/shipdoc/global/kakao/NearbySearchService.java
  src/main/java/com/shipdoc/global/kakao/dto/KakaoResponseDto.java
Labels: :sparkles: feature, :recycle: refactor

#25 ✨ FEAT. 리마인드 문자 발송 기능 구현
  src/main/java/com/shipdoc/domain/Member/entity/mapping/Reservation.java
  src/main/java/com/shipdoc/domain/reservation/converter/ReservationConverter.java
  src/main/java/com/shipdoc/domain/reservation/exception/ReservationNotExistException.java
  src/main/java/com/shipdoc/domain/reservation/service/ReservationCommandService.java
  src/main/java/com/shipdoc/domain/reservation/service/ReservationCommandServiceImpl.java
  src/main/java/com/shipdoc/domain/reservation/web/controller/ReservationRestController.java
  src/main/java/com/shipdoc/global/config/SchedulerConfig.java
  src/main/java/com/shipdoc/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/shipdoc/global/service/SchedulerService.java
  src/main/java/com/shipdoc/global/sms/NurigoSmsServiceImpl.java
  src/main/java/com/shipdoc/global/sms/SmsSentService.java
Labels: :sparkles: feature

#27 :sparkles: FEAT. 예약 => 진료 데이터 변경 API 기능 구현
  src/main/java/com/shipdoc/domain/Member/entity/Patient.java
  src/main/java/com/shipdoc/domain/consultation/converter/ConsultationConverter.java
  src/main/java/com/shipdoc/domain/consultation/entity/Consultation.java
  src/main/java/com/shipdoc/domain/consultation/repository/ConsultationRepository.java
  src/main/java/com/shipdoc/domain/consultation/service/ConsultationCommandService.java
  src/main/java/com/shipdoc/domain/consultation/service/ConsultationCommandServiceImpl.java
  src/main/java/com/shipdoc/domain/consultation/web/controller/ConsultationRestController.java
  src/main/java/com/shipdoc/domain/consultation/web/dto/ConsultationRequestDto.java
  src/main/java/com/shipdoc/domain/consultation/web/dto/ConsultationResponseDto.java
  src/main/java/com/shipdoc/domain/hospital/entity/Hospital.java
Labels: :sparkles: feature

#31 ✨ FEAT. 병원 예약 및 진료 내역 조회 항목 추가
  src/main/java/com/shipdoc/domain/consultation/service/ConsultationQueryServiceImpl.java
  src/main/java/com/shipdoc/domain/consultation/web/dto/ConsultationListDto.java
  src/main/java/com/shipdoc/domain/reservation/service/ReservationQueryServiceImpl.java
  src/main/java/com/shipdoc/domain/reservation/web/dto/ReservationListDto.java
  src/main/java/com/shipdoc/global/gpt/GptService.java
Labels: :sparkles: feature

#32 ✨ FEAT. chatbot 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/shipdoc/domain/chatbot/config/ChatConfig.java
  src/main/java/com/shipdoc/domain/chatbot/controller/ChatController.java
  src/main/java/com/shipdoc/domain/chatbot/entity/Chat.java
  src/main/java/com/shipdoc/domain/chatbot/enums/Specialization.java
  src/main/java/com/shipdoc/domain/chatbot/exception/CustomException.java
  src/main/java/com/shipdoc/domain/chatbot/repository/ChatRepository.java
  src/main/java/com/shipdoc/domain/chatbot/service/ChatService.java
  src/main/java/com/shipdoc/domain/chatbot/service/IChatService.java
Labels: :sparkles: feature
